version: '3.8'

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://root:sentey2311@cluster0.ep1fq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: aluxion_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
